services:
  churchbe.gateway:
    image: ${DOCKER_REGISTRY-}churchbe
    container_name: ChurchBE.Gateway
    depends_on:
      - churchbe.database
    build:
      context: .
      dockerfile: src/API/ChurchBE.Gateway/Dockerfile

  churchbe.users.api:
    image: ${DOCKER_REGISTRY-}churchbeusersapi
    container_name: ChurchBE.Users.API
    build:
      context: .
      dockerfile: src/API/ChurchBE.Users.API/Dockerfile

  churchbe.database:
    image: postgres:latest
    container_name: ChurchBE.Database
    environment:
      - POSTGRES_DB=churchbe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      #- ./.containers/db:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  churchbe.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: ChurchBE.Identity
    depends_on:
      - churchbe.database
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080

  churchbe.seq:
    image: datalust/seq:latest
    container_name: ChurchBE.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - 5341:5341
      - 8081:80

  churchbe.redis:
    image: redis:latest
    container_name: ChurchBE.Redis
    restart: always
    ports:
      - 6380:6379

  churchbe.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ChurchBE.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  churchbe.queue:
    image: rabbitmq:management-alpine
    container_name: ChurchBE.Queue
    hostname: churchbe-queue
    volumes:
        #- ./.containers/queue/data/:/var/lib/rabbitmq
        #- ./.containers/queue/log/:/var/log/rabbitmq
        - queue-data:/var/lib/rabbitmq
        - queue-log:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

